version: '3.7'

services:

  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: majo2022
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
    networks:
      - farmstack

  backend:
    build: backend
    ports:
      - 8000:8000
    networks:
      - farmstack
      
  frontend:
    build: frontend
    ports:
      - 80:80      
    networks:
      - farmstack 
   
networks:
  farmstack:
    
      
volumes:
  mongodb_data:
